### ISSUE TITLE
Explain "will not function properly"

### ISSUE THREAD

**Issue by broofa** [eblume/node-gmail#3]
"This is a work in progress and will not function properly" is nice to know, but without elaboration on what may / may not function properly, it's essentially means "DO NOT USE". (which is fine, if that's your intent I suppose :) )

**Comment by eblume** [comment]
That's basically the effect at the moment. When I have some free time again I plan on revving this up to 1.0 when that notice will be dropped.

If it helps, the entire remote operation is forced in to a READ ONLY mode, so the absolute worst the program should be capable of us being un-useful and using up disk space for the emails it downloads.

I can, however, say that it works for me.

**Comment by broofa** [comment]
Yeah, no worries.  You might want to add something to that effect right below the warning in the meantime though.

'Said my piece.  Feel free to close. :)

**Comment by eblume** [comment]
No I think I'll leave it open because it might shame me in to doing something about it. Thanks. ;)

If the net effect is that it scares people away from using it, that's probably for the best. The current state of the code... leaves much to be desired.

**Comment by broofa** [comment]
fwiw, I've gone straight to node-imap and am finding it to be pretty darn sweet.  Nice little module, that.  Very easy to use, especially since the example provides the necessary gmail configuration :)

**Comment by eblume** [comment]
Yeah - node-gmail is just a wrapper for node-imap (as I'm sure you know). The purpose in creating it was to reduce code complexity for another project. I could have wrapped it in to that project as an embedded library but I also wanted to teach myself how to use npm.

**Comment by eblume** [comment]
(And, not to be at all offensive to the author of node-imap, but the documentation at the time I wrote this had some serious formatting issues. Writing this library actually helped fix a lot of the node-imap documentation.)

**Comment by broofa** [comment]
_heh_ I was just admiring the node-imap documentation so... thanks!
